### ISSUE TITLE
QSD or ? not considered

### ISSUE THREAD

**Issue by jcfr** [madewithlove/htaccess.madewithlove.be#57]
To reproduce:

### case 1: Use of `QSD`
```
http://foo.bar/my/api/rest?method=download&checksum=1234&name=file.zip
```

```
rewritecond %{QUERY_STRING}  ^method=download&checksum=1234&name=file.zip$
rewriterule ^.*$ https://other.bar/api/v1/file/hashsum/sha512/abcdef/download[R=302,L,QSD]
```

![image](https://user-images.githubusercontent.com/219043/46633266-33e4fa80-cb1b-11e8-83a4-a7888029735c.png)

Expected output: `https://other.bar/api/v1/file/hashsum/sha512/abcdef/download`

### case 2: Use of `?`

```
http://foo.bar/my/api/rest?method=download&checksum=1234&name=file.zip
```

```
rewritecond %{QUERY_STRING}  ^method=download&checksum=1234&name=file.zip$
rewriterule ^.*$ https://other.bar/api/v1/file/hashsum/sha512/abcdef/download?[R=302,L]
```

![image](https://user-images.githubusercontent.com/219043/46633301-4bbc7e80-cb1b-11e8-87d4-7331d212d8dc.png)

Expected output: `https://other.bar/api/v1/file/hashsum/sha512/abcdef/download`

**Comment by WouterSioen** [comment]
Hi Jean-Christophe,

I was testing your issue and it seems to me like your first example is implemented correctly. (As you can see here: https://htaccess.madewithlove.be?share=7353d45d-32d6-51a1-92d4-7c90d47f79b9)

The issue is that you forgot to put a space in between your rewrite rule and the flags.


The second one has the same issue (forgot a space) but there is indeed an inconsistency between our application when the rewriterule destination ends in a question mark which we are going to fix.

**Comment by jcfr** [comment]
Hi @WouterSioen , 

Thanks for the follow up :smile: 

> The issue is that you forgot to put a space in between your rewrite rule and the flags.

Good catch. Thanks for letting me know.

> indeed an inconsistency between our application when the rewriterule destination ends in a question mark which we are going to fix. 

:+1:

**Comment by WouterSioen** [comment]
Hey Jean-Christophe,

We just deployed a change that fixed the issues with your second case. Thanks for the bug report!

**Comment by jcfr** [comment]
Thanks for the update
