### ISSUE TITLE
Rewrite rule without regex should match the whole word

### ISSUE THREAD

**Issue by andreascreten** [madewithlove/htaccess.madewithlove.be#6]
> Thanks for this useful tool. But it's not working for me in the case of a partial match. If I put
> 
> RewriteRule page1 page2 
> 
> It shows that http://example.com/page1.htm will be changed to http://example.com/page2.htm. 
> 
> This is not what happens on my real server. The replacement string _completely replaces_ the original. It does not do in-string substitution. So the real server gets http://example.com/page2 without the .htm extension.

_[Filed by Bob on Mon, 12 Aug 2013 13:50:04 CET](http://madewithlove.be/abob/2011/04/simple-htaccess-tester/#comment-3784)_

**Comment by WouterSioen** [comment]
Can't reproduce. Apache redirects to `http://example.com/page2.htm`, not to `http://example.com/page2`

**Comment by WouterSioen** [comment]
That's not true, apache doesn't do a redirect because it does not match `http://example.com/page1.htm`

**Comment by WouterSioen** [comment]
Didn't add the `R` flag. But the behaviour is still different from what's happening in apache though.

Document: `RewriteRule page1 page2 [R]`
url: `http://localhost/page1.htm`
output: `http://localhost/usr/local/apache2/htdocs/page2`

Not sure if this is due to a configuration issue or something different.
